#!/bin/bash
set -e

# Initial setup
uuid=$(python3 -c "import uuid; print(uuid.uuid4())")
sudo xargs -a packages.txt apt install -y
sudo mkdir -v -p /etc/node_rpi
sudo mkdir -v -p /srv/node_rpi
sudo mkdir -v -p /srv/node_rpi/html
echo -e "\n"
sudo cp -v html/*.* /srv/node_rpi/html/
if [ -f "/etc/node_rpi/config.json" ]; then
    timestamp=$(date +%Y%m%d%H%M%S)
    sudo cp -v /etc/node_rpi/config.json "/etc/node_rpi/config.json-$timestamp"
fi    
sudo cp -v default-config.json /etc/node_rpi/config.json
sudo sed -i "s/node-id-notset/$uuid/g" /etc/node_rpi/config.json
echo -e "\n"
